[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "server/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
